version: '3.8'
services:
  database:
    image: mysql:latest
    container_name: database
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
        - dev
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    links:
      - database
    environment:
      PMA_HOST: database
    ports:
      - "8081:80"
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev
    
    ports:
      - "1080:1080"

  www:
    build: docker
    container_name: www
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev


networks:
    dev:

volumes:
    db-data:
